CREATE DATABASE spring_database;

CREATE TABLE register (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    birthdate DATE,
    created_at TIMESTAMP,
    email VARCHAR(255),
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    password VARCHAR(255),
    role VARCHAR(25) NOT NULL CHECK (role IN ('ROLE_ADMIN','ROLE_USUARIO')),
    summary VARCHAR(255),
    updated_at TIMESTAMP,
    username VARCHAR(255),
    PRIMARY KEY (id)
);