CREATE TABLE register (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                          first_name VARCHAR(255),
                          last_name VARCHAR(255),
                          username VARCHAR(255),
                          email VARCHAR(255),
                          password VARCHAR(255),
                          role VARCHAR(25) NOT NULL CHECK (role IN ('ROLE_ADMIN', 'ROLE_USUARIO')),
                          PRIMARY KEY (id)
);


CREATE TABLE post (
                      postId BIGINT GENERATED BY DEFAULT AS IDENTITY,
                      text VARCHAR(280),
                      userId BIGINT,
                      authorId BIGINT,
                      author VARCHAR(255),
                      likes INT DEFAULT 0,
                      reposts INT DEFAULT 0,
                      numberComments INT DEFAULT 0,
                      createdAt TIMESTAMP,
                      updatedAt TIMESTAMP,
                      PRIMARY KEY (postId),
                      FOREIGN KEY (userId) REFERENCES register(id),
                      FOREIGN KEY (authorId) REFERENCES register(id) ON DELETE CASCADE
);
